"""Public interface for the dependency-free Sheath Stage-0 core."""

from .artifacts import ArtifactError, ArtifactStore, StoredArtifact
from .contracts import (
    Constraint,
    ContractError,
    RepositorySnapshot,
    SuccessCriterion,
    TaskContract,
    task_contract_from_record,
)
from .coordinator import (
    BoundedAttemptResult,
    CoordinatorError,
    ProposalVerifier,
    SingleAttemptResult,
    VerificationReport,
    run_bounded_attempts,
    run_single_attempt,
)
from .cyxcode import (
    CyxCodeExecution,
    CyxCodeExecutor,
    CyxCodeGenerator,
    SubprocessCyxCodeExecutor,
    TrustedPatchExtractor,
    build_cyxcode_prompt,
    restore_cyxcode_metadata,
)
from .decision import Decision, Finding, Severity, Verdict, decide
from .docker_backend import (
    CliResult,
    DockerBackendError,
    DockerCliBackend,
    DockerSandboxConfig,
    DockerTransport,
)
from .generator import (
    GenerationRequest,
    GeneratorAdapter,
    GeneratorError,
    GeneratorProposal,
    ValidatedProposal,
    validate_proposal,
)
from .ledger import Evidence, EvidenceLedger, LedgerError, LedgerEvent
from .patch_application import PatchApplication, PatchApplier
from .patches import DockerPatchExtractor, PatchError, PatchExtraction
from .records import (
    RunBudget,
    RunMetadata,
    RunMetrics,
    RunRecordError,
    build_run_record,
    encode_run_record,
    run_record_digest,
)
from .runner import (
    ConstrainedRunner,
    ExecutionOutcome,
    RunnerError,
    SandboxBackend,
    SandboxProfile,
    SandboxRequest,
    SandboxResult,
)
from .snapshots import (
    SnapshotError,
    SnapshotStager,
    WorkspaceBinding,
    WorkspaceSnapshot,
    directory_digest,
    read_only_workspace,
)
from .state import RunState, RunStateMachine, StateError, StateTransition
from .tools import (
    Authorization,
    CommandAction,
    CommandPolicy,
    ExecutableIdentity,
    Observation,
    ToolBoundaryError,
    ToolSession,
    digest_bytes,
    identify_container_executable,
    identify_executable,
)
from .verification import ToolBackedVerifier, ToolCheck

__all__ = [
    "Constraint",
    "ContractError",
    "CoordinatorError",
    "CyxCodeExecution",
    "CyxCodeExecutor",
    "CyxCodeGenerator",
    "ArtifactError",
    "ArtifactStore",
    "BoundedAttemptResult",
    "CommandAction",
    "CommandPolicy",
    "ConstrainedRunner",
    "Decision",
    "DockerBackendError",
    "DockerCliBackend",
    "DockerPatchExtractor",
    "DockerSandboxConfig",
    "DockerTransport",
    "Evidence",
    "EvidenceLedger",
    "ExecutableIdentity",
    "ExecutionOutcome",
    "Finding",
    "GenerationRequest",
    "GeneratorAdapter",
    "GeneratorError",
    "GeneratorProposal",
    "Authorization",
    "LedgerError",
    "LedgerEvent",
    "CliResult",
    "RepositorySnapshot",
    "Observation",
    "PatchApplication",
    "PatchApplier",
    "PatchError",
    "PatchExtraction",
    "ProposalVerifier",
    "RunBudget",
    "RunMetadata",
    "RunMetrics",
    "RunRecordError",
    "RunState",
    "RunStateMachine",
    "RunnerError",
    "SandboxBackend",
    "SandboxProfile",
    "SandboxRequest",
    "SandboxResult",
    "Severity",
    "SuccessCriterion",
    "StateError",
    "StateTransition",
    "StoredArtifact",
    "SubprocessCyxCodeExecutor",
    "SingleAttemptResult",
    "SnapshotError",
    "SnapshotStager",
    "TaskContract",
    "TrustedPatchExtractor",
    "ToolBoundaryError",
    "ToolBackedVerifier",
    "ToolCheck",
    "ToolSession",
    "ValidatedProposal",
    "VerificationReport",
    "Verdict",
    "WorkspaceBinding",
    "WorkspaceSnapshot",
    "build_run_record",
    "build_cyxcode_prompt",
    "decide",
    "directory_digest",
    "digest_bytes",
    "encode_run_record",
    "identify_container_executable",
    "run_record_digest",
    "run_bounded_attempts",
    "run_single_attempt",
    "restore_cyxcode_metadata",
    "identify_executable",
    "read_only_workspace",
    "task_contract_from_record",
    "validate_proposal",
]
