"""Deterministic subprocess fixture for the Python CyxCode bridge boundary."""

import hashlib
import json
from pathlib import Path
import sys


def redact(value, key=""):
    if any(name in key.lower() for name in ("key", "token", "secret", "password", "credential")):
        return "<redacted>"
    if isinstance(value, dict):
        return {name: redact(item, name) for name, item in value.items()}
    if isinstance(value, list):
        return [redact(item) for item in value]
    return value


request = json.loads(sys.stdin.buffer.read())
prompt = request["prompt"].encode("utf-8")
if request["prompt_digest"] != "sha256:" + hashlib.sha256(prompt).hexdigest():
    raise SystemExit("prompt digest mismatch")

snapshot = Path(request["snapshot"])
(snapshot / "generated.txt").write_text("generated by bridge\n", encoding="utf-8")
environment_digest = "sha256:" + "7" * 64
envelope = {
    "schema_version": "1.0.0",
    "status": "ok",
    "failure_reason": None,
    "prompt_digest": request["prompt_digest"],
    "environment_digest": environment_digest,
    "request": {
        "prompt": request["prompt"],
        "model": request["model"],
        "title": request["title"],
        "variant": request["variant"],
        "config": redact(request["config"]),
        "executable_digest": request["executable_digest"],
    },
    "execution": {
        "status": "ok",
        "environmentDigest": environment_digest.removeprefix("sha256:"),
        "stateRemoved": True,
        "run": {"argv": ["fixture"], "exitCode": 0},
    },
}
sys.stdout.buffer.write(
    (json.dumps(envelope, sort_keys=True, separators=(",", ":")) + "\n").encode(
        "utf-8"
    )
)
